
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otus-msa-ingress
  namespace: otus-msa
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: otus-msa-service
            port:
              number: 80
