
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: otus-msa-ingress
  namespace: otus-msa
spec:
  rules:
  - host: arch.homework
    http:
      paths:
      - path: /otus-msa-service/stepan/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: otus-msa-service
            port:
              number: 80
